package com.testwork.hotels.di

const val NAMED_GET_HOTEL_USE_CASE = "NAMED_GET_HOTEL_USE_CASE"

const val NAMED_GET_NUMBERS_USE_CASE = "NAMED_GET_NUMBERS_USE_CASE"

const val NAMED_GET_RESERVATION_USE_CASE = "NAMED_GET_RESERVATION_USE_CASE"